PansiyonTransilvaniye/Models/Odalar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PansiyonTransilvaniye.Models
{
    public class Odalar
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Oda Ücreti")]
        public int OdaUcreti { get; set; }
        [Required]
        [DisplayName("Oda Adı")]
        public string OdaAdi { get; set; }
        [Required]
        [DisplayName("Oda Özellikleri")]
        [StringLength(10000)]
        [AllowHtml]
        public string OdaOzellikleri { get; set; }
        [DisplayName("Oda resimi")]
        public byte[] OdaResimleri { get; set; }
      
    }
}

PansiyonTransilvaniye/Areas/Admin/Controllers/OdalarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PansiyonTransilvaniye.DAL;
using PansiyonTransilvaniye.Models;

namespace PansiyonTransilvaniye.Areas.Admin.Controllers
{
    public class OdalarsController : Controller
    {
        private PansiyonContext db = new PansiyonContext();

        // GET: Admin/Odalars
        public ActionResult Index()
        {
            return View(db.odalar.ToList());
        }

        // GET: Admin/Odalars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Odalar odalar = db.odalar.Find(id);
            if (odalar == null)
            {
                return HttpNotFound();
            }
            return View(odalar);
        }

        // GET: Admin/Odalars/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Odalars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OdaUcreti,OdaAdi,OdaOzellikleri,OdaResimleri")] Odalar odalar, HttpPostedFileBase OdaResimi)
        {
            if (ModelState.IsValid && OdaResimi != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(OdaResimi.InputStream))
                {
                    imageData = binaryReader.ReadBytes(OdaResimi.ContentLength);
                }
                odalar.OdaResimleri = imageData;
                db.odalar.Add(odalar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(odalar);
        }

        // GET: Admin/Odalars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Odalar odalar = db.odalar.Find(id);
            if (odalar == null)
            {
                return HttpNotFound();
            }
            return View(odalar);
        }

        // POST: Admin/Odalars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OdaUcreti,OdaAdi,OdaOzellikleri,OdaResimleri")] Odalar odalar,HttpPostedFileBase OdaResimi)
        {
            if (ModelState.IsValid)
            {
                
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(OdaResimi.InputStream))
                {
                    imageData = binaryReader.ReadBytes(OdaResimi.ContentLength);
                }
                odalar.OdaResimleri = imageData;
                db.Entry(odalar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(odalar);
        }

        // GET: Admin/Odalars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Odalar odalar = db.odalar.Find(id);
            if (odalar == null)
            {
                return HttpNotFound();
            }
            return View(odalar);
        }

        // POST: Admin/Odalars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Odalar odalar = db.odalar.Find(id);
            db.odalar.Remove(odalar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PansiyonTransilvaniye/Areas/Admin/Views/Odalars/Create.cshtml
@model PansiyonTransilvaniye.Models.Odalar
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/Scripts/ckeditor/ckeditor.js"></script>

<h2>Oda Ekleme Sayfası</h2>


@using (Html.BeginForm("Create", "Odalars", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OdaUcreti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OdaUcreti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OdaUcreti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OdaAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OdaAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OdaAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OdaOzellikleri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextArea("OdaOzellikleri")
                <script type="text/javascript">
                    var editor = CKEDITOR.instances['OdaOzellikleri'];
                    if (editor) { editor.destroy(true); }
                    CKEDITOR.replace('OdaOzellikleri', {
                        enterMode: CKEDITOR.ENTER_BR,

                    });
                </script>
                @Html.ValidationMessageFor(model => model.OdaOzellikleri, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.LabelFor(model => model.OdaResimleri, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="OdaResimi" />
            @Html.ValidationMessageFor(model => model.OdaResimleri, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class=" btn btn-primary" , style="background-color:#2fee50" />
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PansiyonTransilvaniye/Areas/Admin/Views/Odalars/Delete.cshtml
@model PansiyonTransilvaniye.Models.Odalar
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sil</h2>


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OdaUcreti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaUcreti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OdaAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OdaOzellikleri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaOzellikleri)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class=" btn btn-primary" , style="background-color:#2fee50" />
            @Html.ActionLink("Odalara Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
        </div>
    }
</div>

PansiyonTransilvaniye/Areas/Admin/Views/Odalars/Index.cshtml
@model IEnumerable<PansiyonTransilvaniye.Models.Odalar>
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Odalar</h2>

<p>
    @Html.ActionLink("Oda Ekle", "Create", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OdaUcreti)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OdaAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OdaOzellikleri)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OdaResimleri)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OdaUcreti)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OdaAdi)
            </td>
            <td>
                @Html.Raw(item.OdaOzellikleri)
            </td>
            <td>
                @Html.Raw("<img style='width:100px; height:100px;' src=\"data:image/jpeg;base64,"
                                     + Convert.ToBase64String(item.OdaResimleri) + "\" />")
            </td>
            <td>
                @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
            </td>
        </tr>
    }

</table>