PansiyonTransilvaniye/Models/Galeri.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace PansiyonTransilvaniye.Models
{
    public class Galeri
    {
        public int Id { get; set; }
        [DisplayName("Galeri Sayfa Resimleri")]
        public byte[] GaleriResimler { get; set; }
    }
}

PansiyonTransilvaniye/Areas/Admin/Controllers/GalerisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PansiyonTransilvaniye.DAL;
using PansiyonTransilvaniye.Models;

namespace PansiyonTransilvaniye.Areas.Admin.Controllers
{
    public class GalerisController : Controller
    {
        private PansiyonContext db = new PansiyonContext();

        // GET: Admin/Galeris
        public ActionResult Index()
        {
            return View(db.galeri.ToList());
        }

      
        // GET: Admin/Galeris/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Galeris/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,GaleriResimler")] Galeri galeri, HttpPostedFileBase Galeriler)
        {
            if (ModelState.IsValid && Galeriler != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(Galeriler.InputStream))
                {
                    imageData = binaryReader.ReadBytes(Galeriler.ContentLength);
                }
                galeri.GaleriResimler = imageData;
                db.galeri.Add(galeri);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(galeri);
        }

       
        // GET: Admin/Galeris/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Galeri galeri = db.galeri.Find(id);
            if (galeri == null)
            {
                return HttpNotFound();
            }
            return View(galeri);
        }

        // POST: Admin/Galeris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Galeri galeri = db.galeri.Find(id);
            db.galeri.Remove(galeri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PansiyonTransilvaniye/Areas/Admin/Views/Galeris/Create.cshtml
@model PansiyonTransilvaniye.Models.Galeri
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Galeri Resim Ekle</h2>


@using (Html.BeginForm("Create", "Galeris", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Galeri</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.LabelFor(model => model.GaleriResimler, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Galeriler" />
            @Html.ValidationMessageFor(model => model.GaleriResimler, "", new { @class = "text-danger" })
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class=" btn btn-primary" , style="background-color:#2fee50" />
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PansiyonTransilvaniye/Areas/Admin/Views/Galeris/Delete.cshtml
@model PansiyonTransilvaniye.Models.Galeri
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sil</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GaleriResimler)
        </dt>

        <dd>
            @Html.Raw("<img style='width:100px; height:100px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(Model.GaleriResimler) + "\" />")
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class=" btn btn-primary" , style="background-color:#2fee50" />
            @Html.ActionLink("Odalara Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
        </div>
    }
</div>

PansiyonTransilvaniye/Areas/Admin/Views/Galeris/Index.cshtml
@model IEnumerable<PansiyonTransilvaniye.Models.Galeri>
@if (Session["Id"] == null)
{
    Response.Redirect("~/Login/Loged");
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Galeri Resimleri</h2>

<p>
    @Html.ActionLink("Resim Ekle", "Create", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GaleriResimler)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.Raw("<img style='width:100px; height:100px;' src=\"data:image/jpeg;base64,"
                                    + Convert.ToBase64String(item.GaleriResimler) + "\" />")
            </td>
            <td>
                @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })

            </td>
        </tr>
    }

</table>