PansiyonTransilvaniye/Models/AnaSayfaResimler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace PansiyonTransilvaniye.Models
{
    public class AnaSayfaResimler
    {
        public int Id { get; set; }
        [DisplayName("Ana Sayfa Resimleri")]
        public byte[] AnaSayfaResimleri { get; set; }
       
    }
}

PansiyonTransilvaniye/Areas/Admin/Controllers/AnaSayfaResimlersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PansiyonTransilvaniye.DAL;
using PansiyonTransilvaniye.Models;

namespace PansiyonTransilvaniye.Areas.Admin.Controllers
{
    public class AnaSayfaResimlersController : Controller
    {
        private PansiyonContext db = new PansiyonContext();

        // GET: Admin/AnaSayfaResimlers
        public ActionResult Index()
        {
            return View(db.anaSayfaResimler.ToList());
        }

       
        // GET: Admin/AnaSayfaResimlers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AnaSayfaResimlers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AnaSayfaResimleri")] AnaSayfaResimler anaSayfaResimler, HttpPostedFileBase AnaSayfa)
        {
            if (ModelState.IsValid && AnaSayfa!=null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(AnaSayfa.InputStream))
                {
                    imageData = binaryReader.ReadBytes(AnaSayfa.ContentLength);
                }
                anaSayfaResimler.AnaSayfaResimleri = imageData;
                db.anaSayfaResimler.Add(anaSayfaResimler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(anaSayfaResimler);
        }

       
        // GET: Admin/AnaSayfaResimlers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnaSayfaResimler anaSayfaResimler = db.anaSayfaResimler.Find(id);
            if (anaSayfaResimler == null)
            {
                return HttpNotFound();
            }
            return View(anaSayfaResimler);
        }

        // POST: Admin/AnaSayfaResimlers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnaSayfaResimler anaSayfaResimler = db.anaSayfaResimler.Find(id);
            db.anaSayfaResimler.Remove(anaSayfaResimler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PansiyonTransilvaniye/Areas/Admin/Views/AnaSayfaResimlers/Create.cshtml
@model PansiyonTransilvaniye.Models.AnaSayfaResimler

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Ana Sayfa Resim Ekle</h2>


@using (Html.BeginForm("Create", "AnaSayfaResimlers", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     
            @Html.LabelFor(model => model.AnaSayfaResimleri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="AnaSayfa" />
                @Html.ValidationMessageFor(model => model.AnaSayfaResimleri, "", new { @class = "text-danger" })
            </div>
      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class=" btn btn-primary" , style="background-color:#2fee50" />
                @Html.ActionLink("Geri Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PansiyonTransilvaniye/Areas/Admin/Views/AnaSayfaResimlers/Delete.cshtml
@model PansiyonTransilvaniye.Models.AnaSayfaResimler

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sil</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AnaSayfaResimleri)
        </dt>

        <dd>
            @Html.Raw("<img style='width:100px; height:100px;' src=\"data:image/jpeg;base64,"
                               + Convert.ToBase64String(Model.AnaSayfaResimleri) + "\" />")
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Sil" class=" btn btn-primary" , style="background-color:#2fee50" />
        @Html.ActionLink("Odalara Dön", "Index", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
    </div>
    }
</div>

PansiyonTransilvaniye/Areas/Admin/Views/AnaSayfaResimlers/Index.cshtml
@model IEnumerable<PansiyonTransilvaniye.Models.AnaSayfaResimler>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Ana Sayfa Resimi</h2>

<p>
    @Html.ActionLink("Resim Ekle", "Create", null, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AnaSayfaResimleri)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.Raw("<img style='width:100px; height:100px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(item.AnaSayfaResimleri) + "\" />")
        </td>
        <td>
            @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = " btn btn-primary", @style = "background-color:#2fee50" })

        </td>
    </tr>
}

</table>